### ISSUE TITLE
I have an issue in the code "nav_node.py".

### ISSUE THREAD

**Issue by LEEJUHUI6635** [MIT-SPARK/Loc-NeRF#2]
Firstly, thanks for your nice research. 

![스크린샷, 2022-11-18 20-06-59](https://user-images.githubusercontent.com/98508690/202692006-fb429b08-3d03-4e41-b759-85f6f9cd08f5.png)

I had the above issue.
I printed "start_file.split('_')[5]" and it just return "fern". Then, how to make "fern" into any int type number?

Thank you.

**Comment by Dominic101** [comment]
Hi, since you are hitting that block of code you have `use_logged_start: True` in your yaml. That means the code is looking inside one of the logs folders to get the initial starting pose. Please confirm you have your `log_directory` parameter set to be a path to this folder https://github.com/MIT-SPARK/Loc-NeRF/tree/0d859be5e489f46053082bef162eef692f03dc54/logs/inerf_compare. If that is correct and it still doesn't work, then print out start_file.split('_') and post the output here

**Comment by LEEJUHUI6635** [comment]
Thank you for your response. I have solved it.
