### ISSUE TITLE
Questions about why use VIO algorithms

### ISSUE THREAD

**Issue by LEEJUHUI6635** [MIT-SPARK/Loc-NeRF#3]
Hello. First of all, thank you for your wonderful research.

I have a few questions about why you use VIO algorithms.

First, according to your paper, I understood that the reason is to put odometry information in the prediction stage of montecarlo localization, and to perform geo-registration due to non-scale problem of colmap. Is my understanding correct?

When I performed VINS-Fusion with my custom dataset to get an odometry information, VINS-Fusion algorithm itself could not produce accurate results. Therefore, I want to obtain more accurate odometry information with ORB-SLAM algorithm. I wonder whether your open source can use any algorithm that can provide odometry.

Thanks once again.

**Comment by Dominic101** [comment]
VIO is only used in the predict step if you have a moving camera (i.e. we do not use VIO on the LLFF dataset experiments but we do use it when we test on a moving robot). You are correct that as is traditional for a particle filter, there is some relative, noisy estimate that is used to propagate the particles (that estimate is VIO in our experiment). 

You can easily use any odometry source for Loc-NeRF's predict step. It doesn't have to be VINS-Fusion and it doesn't actually have to be VIO (i.e. it could be an IMU or wheel encoders for example). Since Loc-NeRF is built with ROS support, you simply need to subscribe to whatever odometry source you want by changing the ROS topic here https://github.com/MIT-SPARK/Loc-NeRF/blob/main/cfg/jackal.yaml#L43 and changing the rotation between odometry and NeRF frame here https://github.com/MIT-SPARK/Loc-NeRF/blob/main/cfg/jackal.yaml#L66.

Note that its expected that you VIO estimate will be prone to drift as one role of the update steps is to correct pose errors.

**Comment by LEEJUHUI6635** [comment]
Thank you. I think your specific answer will be helpful for my research.
